// <auto-generated />
namespace bie.focuscrm.ui.mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class manytomany1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(manytomany1));
        
        string IMigrationMetadata.Id
        {
            get { return "201702281659332_manytomany1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
