// <auto-generated />
namespace bie.focuscrm.infra.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NovoCampoEmail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NovoCampoEmail));
        
        string IMigrationMetadata.Id
        {
            get { return "201704182102322_NovoCampoEmail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
